### ----------------------------------------------------------------------------
### SWAGGER DOCUMENTATION UI (Buka di Browser)
### http://localhost:8080/swagger/index.html
### ----------------------------------------------------------------------------

@baseUrl = http://localhost:8080

### ----------------------------------------------------------------------------
### 1. REGISTER USER BUDI (Otomatis dapat Nomor Rekening 10-digit & PIN 123456)
### ----------------------------------------------------------------------------
# @name registerBudi
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "budi",
  "password": "password123",
  "pin": "123456",
  "initial_balance": 1000000
}

### Tangkap Token JWT & Account ID Budi
@tokenBudi = {{registerBudi.response.body.token}}
@accIDBudi = {{registerBudi.response.body.user.account_id}}


### ----------------------------------------------------------------------------
### 2. REGISTER USER SITI (PIN 654321, Saldo Rp 500.000)
### ----------------------------------------------------------------------------
# @name registerSiti
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "siti",
  "password": "password456",
  "pin": "654321",
  "initial_balance": 500000
}

### Tangkap Account ID Siti
@accIDSiti = {{registerSiti.response.body.user.account_id}}


### ----------------------------------------------------------------------------
### 3. LOGIN USER BUDI
### ----------------------------------------------------------------------------
# @name loginBudi
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "username": "budi",
  "password": "password123"
}


### ----------------------------------------------------------------------------
### 4. GET DETAIL REKENING BUDI (Membawa Token JWT)
### ----------------------------------------------------------------------------
GET {{baseUrl}}/accounts/get?id={{accIDBudi}}
Authorization: Bearer {{tokenBudi}}


### ----------------------------------------------------------------------------
### 5. TRANSFER SALDO RP 350.000 DARI BUDI KE SITI (Dengan Verifikasi PIN 123456)
### ----------------------------------------------------------------------------
POST {{baseUrl}}/accounts/transfer
Authorization: Bearer {{tokenBudi}}
Content-Type: application/json

{
  "from_account_id": "{{accIDBudi}}",
  "to_account_id": "{{accIDSiti}}",
  "pin": "123456",
  "amount": 350000,
  "description": "Transfer Bayar Sewa Kos"
}


### ----------------------------------------------------------------------------
### 6. TARIK TUNAI RP 100.000 DI ATM (Dengan Verifikasi PIN 123456)
### ----------------------------------------------------------------------------
POST {{baseUrl}}/accounts/withdraw
Authorization: Bearer {{tokenBudi}}
Content-Type: application/json

{
  "account_id": "{{accIDBudi}}",
  "pin": "123456",
  "amount": 100000
}


### ----------------------------------------------------------------------------
### 7. CEK MUTASI & HISTORI TRANSAKSI REKENING BUDI
### ----------------------------------------------------------------------------
GET {{baseUrl}}/accounts/mutations?account_id={{accIDBudi}}
Authorization: Bearer {{tokenBudi}}
